import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/NedaProfile.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
// import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Code By Neda</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8 ">
          <div className="flex items-center justify-between w-full lg:flex-col">
            {/* profile image */}
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Neda"
                className="w-full h-auto lg:inline-block lg:w-full lg:mt-4"
                priority
                sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw"
              />
            </div>

            {/* right side text */}
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center ">
              <AnimatedText
                text="Hello, I'm Neda. I turn imaginitions into websites."
                className="!text-6xl !text-left
                xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled Full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in python Django,
                React.js and web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Neda-Ramakchi-Resume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 
                  rounded-lg text-lg font-semibold hover:bg-light hover:text-dark 
                  border-2 border--solid border-dark
                  transition-all duration-1000
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:border-light hover:dark:text-light
                  md:p-2 md:px-4 md:text-base
                  "
                  download={true}
                >
                  Resume
                  <LinkArrow className={"!w-5 ml-1"} />
                </Link>
                <Link
                  href="mailto:neda1995aynechi@protonmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline 
                  dark:text-light"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        {/* <div className="absolute right-8 bottom-9 inline-block w-24">
          <Image src={lightBulb} alt="Neda" className="w-full h-auto" />
        </div> */}
      </main>
    </>
  );
}
